# Generated by Django 3.1.6 on 2021-02-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_product', '0002_auto_20210211_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
